// credit.c
// Parthiban Bala
// Program gets imput (credit card number) from the user, which is a long
// checks if the number is valid or not; if valid, type of the card

#include <stdio.h>
#include <cs50.h>
#include <math.h>

int main (void)
{
    // get credit card number, until it is a valid number
    long cc;
    do
    {
       cc = get_long("Number: \n");
    }
    while (cc < 0);

    // check the algorithm
    // tempcc is duplicated cc number; counter counts the digits as per algorithm
    // digit is the single digit generated by mod with 10
    // this is done till number of digits remaining is less than 2 digit number
    long tempcc = cc;
    int counter = 0;
    int digit;
    do
    {
        // identify the first digit by mod 10; remaining digit is added in tempcc
        // counter is added with digit (odd position)
        digit = tempcc % 10;
        tempcc = tempcc / 10;
        counter = counter + digit;
        // do the same process for even digits; multiply by 2 (even position of digits)
        // if it is a 2 digit number, add them to make a single digit number
        digit = tempcc % 10;
        tempcc = tempcc / 10;
        digit = digit * 2;
        if (digit > 9)
        {
            digit = (digit % 10) + (digit / 10);
        }
        counter = counter + digit;
    }
    while (tempcc > 10);
    // add the remainng left out digit;
    // it would be 0 for even number of digit cards and a single digit number for
    // odd number of digit cards
    counter = counter + tempcc;

    // print invalid if it does not follow algorithm
    if (counter % 10 != 0)
    {
        printf("INVALID\n");
    }
    // check the number of digits; duplicate cc as tempcc1
    // reset counter as 0 and do the same algorithm to extract digit one by one
    // counter is added with 1 for each encounter
    long tempcc1 = cc;
    counter = 0;
    if (cc < 10)
    {
        printf("INVALID\n");
    }
    do
    {
        digit = tempcc1 % 10;
        tempcc1 = tempcc1 / 10;
        counter += 1;
    }
    while (tempcc1 > 10);
    // add 1 to counter, as we stopped short of two digit
    counter = counter + 1;

    // at this stage stage, digit is the second digit and tempcc1 is the first digit
    // now we can come to conclusions what is the type of card
    if (counter == 15 && tempcc1 == 3 && (digit == 4 || digit == 7))
    {
        printf("AMEX\n");
    }
    else if (counter == 16 && tempcc1 == 5 && (digit >= 1 && digit <= 5))
    {
        printf("MASTERCARD\n");
    }
    else if ((counter == 13 || counter == 16) && tempcc1 == 4)
    {
        printf("VISA\n");
    }
    else
    {
        printf("INVALID\n");
    }
}
